# Generated by Django 3.0.5 on 2020-05-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200513_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_name', models.TextField()),
                ('id', models.SmallIntegerField(primary_key='True', serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='my_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
        ),
    ]
