# Generated by Django 3.0.5 on 2020-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200521_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='phone',
            field=models.TextField(default='******'),
        ),
    ]
