# Generated by Django 3.0.5 on 2020-05-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_friend_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto'),
        ),
    ]
