# Generated by Django 3.0.5 on 2020-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_book_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='foto/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
